{
 "title": "klokwrk - Axon app - simple metrics",
 "description": "Simple Metrics Dashboard for Axon Framework Apps.",
 "tags": [ "klokwrk" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": { "query": "label_values(app)" } },
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  {
   "title": "Axon Commands",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Success Commands",
     "type": "stat",
     "description": "Total number of success commands",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(commandBus_successCounter_total{app=~\"$application\", instance=~\"$instance\"})by(app)"
      }
     ]
    },
    {
     "title": "Failed Commands",
     "type": "stat",
     "description": "Total number of failed commands",
     "gridPos": { "h": 3, "w": 4, "x": 5, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(commandBus_failureCounter_total{app=~\"$application\", instance=~\"$instance\"}) by (app)"
      }
     ]
    },
    {
     "title": "Processed Commands",
     "type": "stat",
     "description": "Total number of processed\n commands",
     "gridPos": { "h": 3, "w": 4, "x": 10, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(commandBus_processedCounter_total{app=~\"$application\", instance=~\"$instance\"}) by (app)"
      }
     ]
    },
    {
     "title": "Ingested Commands",
     "type": "stat",
     "description": "Total number of ingested\n commands",
     "gridPos": { "h": 3, "w": 4, "x": 15, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(commandBus_ingestedCounter_total{app=~\"$application\", instance=~\"$instance\"}) by(app)"
      }
     ]
    },
    {
     "title": "Ignored Commands",
     "type": "stat",
     "description": "Total number of ignored\n commands",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(commandBus_ignoredCounter_total{app=~\"$application\", instance=~\"$instance\"}) by (app)"
      }
     ]
    },
    {
     "title": "Command Bus Latency (avg)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(commandBus_allTimer_percentile_seconds{app=~\"$application\", instance=~\"$instance\", phi=\"0.5\"})by(app)",
       "legendFormat": "All timer (quantile=\"0.5\")"
      },
      {
       "expr": "avg(commandBus_allTimer_percentile_seconds{app=~\"$application\", instance=~\"$instance\", phi=\"0.75\"})by(app)",
       "legendFormat": "All timer (quantile=\"0.75\")"
      },
      {
       "expr": "avg(commandBus_allTimer_percentile_seconds{app=~\"$application\", instance=~\"$instance\", phi=\"0.95\"})by(app)",
       "legendFormat": "All timer (quantile=\"0.95\")"
      },
      {
       "expr": "avg(commandBus_allTimer_percentile_seconds{app=~\"$application\", instance=~\"$instance\", phi=\"0.999\"})by(app)",
       "legendFormat": "All timer (quantile=\"0.999\")"
      }
     ]
    },
    {
     "title": "Commands Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "sum(irate(commandBus_successCounter_total{app=~\"$application\", instance=~\"$instance\"}[5m])) by (app)",
       "legendFormat": "Success commands"
      },
      {
       "expr": "sum(irate(commandBus_failureCounter_total{app=~\"$application\", instance=~\"$instance\"}[5m])) by (app)",
       "legendFormat": "Failed commands"
      },
      {
       "expr": "sum(irate(commandBus_processedCounter_total{app=~\"$application\", instance=~\"$instance\"}[5m])) by (app)",
       "legendFormat": "Processed commands"
      },
      {
       "expr": "sum(irate(commandBus_ingestedCounter_total{app=~\"$application\", instance=~\"$instance\"}[5m])) by (app)",
       "legendFormat": "Ingested commands"
      },
      {
       "expr": "sum(irate(commandBus_ignoredCounter_total{app=~\"$application\", instance=~\"$instance\"}[5m])) by (app)",
       "legendFormat": "Ignored commands"
      }
     ]
    },
    {
     "title": "Command Bus Capacity",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(commandBus_capacity_ratio{app=~\"$application\", instance=~\"$instance\"}) by (app)",
       "legendFormat": "Command bus"
      }
     ]
    }
   ]
  },
  {
   "title": "Axon Events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Success Events",
     "type": "stat",
     "description": "Total number of success events",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(eventStore_successCounter_total{app=~\"$application\", instance=~\"$instance\"})by(app)"
      }
     ]
    },
    {
     "title": "Failed Events",
     "type": "stat",
     "description": "Total number of failed events",
     "gridPos": { "h": 3, "w": 4, "x": 5, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(eventStore_failureCounter_total{app=~\"$application\", instance=~\"$instance\"})by(app)"
      }
     ]
    },
    {
     "title": "Processed Events",
     "type": "stat",
     "description": "Total number of processed\n events",
     "gridPos": { "h": 3, "w": 4, "x": 10, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(eventStore_processedCounter_total{app=~\"$application\", instance=~\"$instance\"})by(app)"
      }
     ]
    },
    {
     "title": "Ingested Events",
     "type": "stat",
     "description": "Total number of ingested\n events",
     "gridPos": { "h": 3, "w": 4, "x": 15, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(eventStore_ingestedCounter_total{app=~\"$application\", instance=~\"$instance\"})by(app)"
      }
     ]
    },
    {
     "title": "Ignored Events",
     "type": "stat",
     "description": "Total number of ignored\n events",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(eventStore_ignoredCounter_total{app=~\"$application\", instance=~\"$instance\"})by(app)"
      }
     ]
    },
    {
     "title": "Event Bus Latency (avg)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(eventStore_allTimer_percentile_seconds{app=~\"$application\", instance=~\"$instance\", phi=\"0.5\"})by(app)",
       "legendFormat": "All timer (quantile=\"0.5\")"
      },
      {
       "expr": "avg(eventStore_allTimer_percentile_seconds{app=~\"$application\", instance=~\"$instance\", phi=\"0.75\"})by(app)",
       "legendFormat": "All timer (quantile=\"0.75\")"
      },
      {
       "expr": "avg(eventStore_allTimer_percentile_seconds{app=~\"$application\", instance=~\"$instance\", phi=\"0.95\"})by(app)",
       "legendFormat": "All timer (quantile=\"0.95\")"
      },
      {
       "expr": "avg(eventStore_allTimer_percentile_seconds{app=~\"$application\", instance=~\"$instance\", phi=\"0.999\"})by(app)",
       "legendFormat": "All timer (quantile=\"0.999\")"
      }
     ]
    },
    {
     "title": "Events Rate",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "sum(irate(eventStore_successCounter_total{app=~\"$application\", instance=~\"$instance\"}[5m]))by(app)",
       "legendFormat": "Success events"
      },
      {
       "expr": "sum(irate(eventStore_failureCounter_total{app=~\"$application\", instance=~\"$instance\"}[5m]))by(app)",
       "legendFormat": "Failed events"
      },
      {
       "expr": "sum(irate(eventStore_processedCounter_total{app=~\"$application\", instance=~\"$instance\"}[5m]))by(app)",
       "legendFormat": "Processed events"
      },
      {
       "expr": "sum(irate(eventStore_ingestedCounter_total{app=~\"$application\", instance=~\"$instance\"}[5m]))by(app)",
       "legendFormat": "Ingested events"
      },
      {
       "expr": "sum(irate(eventStore_ignoredCounter_total{app=~\"$application\", instance=\"$instance\"}[5m]))by(app)",
       "legendFormat": "Ignored events"
      }
     ]
    }
   ]
  },
  {
   "title": "Axon Queries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Success Queries",
     "type": "stat",
     "description": "Total number of success queries",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(queryBus_successCounter_total{app=~\"$application\", instance=~\"$instance\"})by(app)"
      }
     ]
    },
    {
     "title": "Failed Queries",
     "type": "stat",
     "description": "Total number of failed queries",
     "gridPos": { "h": 3, "w": 4, "x": 5, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(queryBus_failureCounter_total{app=~\"$application\", instance=~\"$instance\"})by(app)"
      }
     ]
    },
    {
     "title": "Processed Queries",
     "type": "stat",
     "description": "Total number of processed\n queries",
     "gridPos": { "h": 3, "w": 4, "x": 10, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(queryBus_processedCounter_total{app=~\"$application\", instance=~\"$instance\"})by(app)"
      }
     ]
    },
    {
     "title": "Ingested Queries",
     "type": "stat",
     "description": "Total number of ingested\n queries",
     "gridPos": { "h": 3, "w": 4, "x": 15, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(queryBus_ingestedCounter_total{app=~\"$application\", instance=~\"$instance\"})by(app)"
      }
     ]
    },
    {
     "title": "Ignored Queries",
     "type": "stat",
     "description": "Total number of ignored\n queries",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(queryBus_ignoredCounter_total{app=~\"$application\", instance=~\"$instance\"})by(app)"
      }
     ]
    },
    {
     "title": "Query Bus Latency (avg)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(queryBus_allTimer_percentile_seconds{app=~\"$application\", instance=~\"$instance\", phi=\"0.5\"})by(app)",
       "legendFormat": "All timer (quantile=\"0.5\")"
      },
      {
       "expr": "avg(queryBus_allTimer_percentile_seconds{app=~\"$application\", instance=~\"$instance\", phi=\"0.75\"})by(app)",
       "legendFormat": "All timer (quantile=\"0.75\")"
      },
      {
       "expr": "avg(queryBus_allTimer_percentile_seconds{app=~\"$application\", instance=~\"$instance\", phi=\"0.95\"})by(app)",
       "legendFormat": "All timer (quantile=\"0.95\")"
      },
      {
       "expr": "avg(queryBus_allTimer_percentile_seconds{app=~\"$application\", instance=~\"$instance\", phi=\"0.999\"})by(app)",
       "legendFormat": "All timer (quantile=\"0.999\")"
      }
     ]
    },
    {
     "title": "Queries Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "sum(irate(queryBus_successCounter_total{app=~\"$application\", instance=~\"$instance\"}[5m]))by(app)",
       "legendFormat": "Success queries"
      },
      {
       "expr": "sum(irate(queryBus_failureCounter_total{app=~\"$application\", instance=~\"$instance\"}[5m]))by(app)",
       "legendFormat": "Failed queries"
      },
      {
       "expr": "sum(irate(queryBus_processedCounter_total{app=~\"$application\", instance=~\"$instance\"}[5m]))by(app)",
       "legendFormat": "Processed queries"
      },
      {
       "expr": "sum(irate(queryBus_ingestedCounter_total{app=~\"$application\", instance=~\"$instance\"}[5m]))by(app)",
       "legendFormat": "Ingested queries"
      },
      {
       "expr": "sum(irate(queryBus_ignoredCounter_total{app=~\"$application\", instance=~\"$instance\"}[5m]))by(app)",
       "legendFormat": "Ignored queries"
      }
     ]
    },
    {
     "title": "Query Bus Capacity",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(queryBus_capacity_ratio{app=~\"$application\", instance=~\"$instance\"})by(app)",
       "legendFormat": "Query bus"
      }
     ]
    }
   ]
  }
 ]
}