spring.application.name: cargotracker-booking-commandside-app

server.port: 8080
server.servlet.context-path: /cargotracker-booking-commandside

axon.axonserver.servers: ${CARGO_TRACKER_AXON_SERVER_HOSTNAME:localhost}:${CARGO_TRACKER_AXON_SERVER_PORT_GRPC:8124}
axon.serializer.general: JACKSON

management.endpoints.web.base-path: /management
management.endpoints.web.exposure.include: '*'
management.endpoint.health.show-details: when_authorized
management.info.git.mode: simple

spring.messages.basename: messages,responseFormattingDefaultMessages

wavefront.application.name: klokwrk-project
wavefront.application.service: ctb-commandside

# TODO dmurat: update Wavefront turn-off template when issue is resolved: https://github.com/wavefrontHQ/wavefront-spring-boot/issues/57
# TODO dmurat: update Axon tracing turn-off template when issue is resolved: https://github.com/AxonFramework/extension-tracing/issues/53
# Template for turning-off Wavefront and Axon tracing. Uncomment it tracing is not desirable.
#spring.autoconfigure.exclude:
#  - com.wavefront.spring.actuate.WavefrontEndpointAutoConfiguration
#  - com.wavefront.spring.autoconfigure.WavefrontAutoConfiguration
#  - org.axonframework.extensions.tracing.autoconfig.TracingAutoConfiguration
#  - org.springframework.boot.actuate.autoconfigure.metrics.export.wavefront.WavefrontMetricsExportAutoConfiguration

logging.pattern.console: "${CONSOLE_LOG_PATTERN:%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(${PID:-}){magenta} %clr([%100.100t]){faint} %clr(%-60.60logger{59}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}}"

logging.level.cargotracker.axon.command-handler-logging: DEBUG       # To see command handler executions.
logging.level.cargotracker.axon.eventsourcing-handler-logging: DEBUG # To see event sourcing handler executions.
logging.level.org.axonframework.eventsourcing: DEBUG
logging.level.org.hibernate.SQL: DEBUG  # To see hibernate statements without parameters
logging.level.org.hibernate.type: TRACE # To see parameters bound to hibernate statements
logging.level.org.klokwrk.cargotracker.lib.axon.cqrs.messagehandler.CommandHandlerTrait: DEBUG # To see original exception stacktrace (before remoting) thrown in axon command handlers.
