version: "3.7"

services:
  klokwrk-project-postgres:
    container_name: klokwrk-project-postgres
    image: postgres:${postgreSqlDockerImageVersion}
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - klokwrk-project-network
    volumes:
      - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./postgres/1-init_db.sh:/docker-entrypoint-initdb.d/1-init_db.sh
      - klokwrk-project-postgres:/data/postgres
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
    restart: unless-stopped

  klokwrk-project-axon-server:
    container_name: klokwrk-project-axon-server
    image: axoniq/axonserver:${axonServerDockerImageVersion}
    hostname: klokwrk-project-axon-server
    ports:
      - "8024:8024"
      - "8124:8124"
      - "8224:8224"
    environment:
      - AXONIQ_AXONSERVER_AUTOCLUSTER_FIRST=klokwrk-project-axon-server
      - AXONIQ_AXONSERVER_AUTOCLUSTER_CONTEXTS=default
      - AXONIQ_AXONSERVER_METRICS_GRPC_ENABLED=true
      - AXONIQ_AXONSERVER_METRICS_GRPC_PROMETHEUS_ENABLED=true
    networks:
      - klokwrk-project-network
    volumes:
      - klokwrk-project-axon-server-data:/data
      - klokwrk-project-axon-server-eventdata:/eventdata
      - klokwrk-project-axon-server-config:/axonserver/config:ro
    restart: unless-stopped

  klokwrk-project-grafana-agent:
    profiles:
      - observability
    container_name: klokwrk-project-grafana-agent
    image: grafana/agent:${grafanaAgentDockerImageVersion}
    hostname: klokwrk-project-grafana-agent
    ports:
      - "4317:4317"
      - "4318:4318"
      - "12345:12345"
    env_file:
      - grafana/grafana-agent/agent.env
    environment:
      - AGENT_MODE=flow
    command: ["run", "--server.http.listen-addr=0.0.0.0:12345", "/etc/agent/config.river"]
    networks:
      - klokwrk-project-network
    volumes:
      - ./grafana/grafana-agent/agent-config.river:/etc/agent/config.river
    restart: unless-stopped

networks:
  klokwrk-project-network:
    name: klokwrk-project-network

volumes:
  klokwrk-project-postgres:
    name: klokwrk-project-postgres
  klokwrk-project-axon-server-data:
    name: klokwrk-project-axon-server-data
  klokwrk-project-axon-server-eventdata:
    name: klokwrk-project-axon-server-eventdata
  klokwrk-project-axon-server-config:
    name: klokwrk-project-axon-server-config
