version: "3.7"

services:
  klokwrk-project-postgres:
    container_name: klokwrk-project-postgres
    image: postgres:12.2
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - klokwrk-project-network
    volumes:
      - ./postgres/1-init-user-db.sh:/docker-entrypoint-initdb.d/1-init-user-db.sh
      - klokwrk-project-postgres:/data/postgres
    restart: unless-stopped

  klokwrk-project-axon-server:
    container_name: klokwrk-project-axon-server
    image: axoniq/axonserver:4.3.3
    ports:
      - 8024:8024
      - 8124:8124
    networks:
      - klokwrk-project-network
    volumes:
      - klokwrk-project-axon-server-data:/data
      - klokwrk-project-axon-server-eventdata:/eventdata
    restart: unless-stopped

networks:
  klokwrk-project-network:
    name: klokwrk-project-network

volumes:
  klokwrk-project-postgres:
    name: klokwrk-project-postgres
  klokwrk-project-axon-server-data:
    name: klokwrk-project-axon-server-data
  klokwrk-project-axon-server-eventdata:
    name: klokwrk-project-axon-server-eventdata
