### cargotracker-booking-commandside, book-cargo, success, hr
POST http://{{host}}:{{port-commandside}}/cargotracker-booking-commandside/book-cargo
Content-Type: application/json
Accept: application/json
Accept-Charset: utf-8
Accept-Language: hr-HR

{
  "originLocation": "HRRJK",
  "destinationLocation": "HRZAG"
}

> {%
// noinspection JSUnresolvedVariable
client.global.set("receivedAggregateIdentifier", response.body.payload.aggregateIdentifier);
%}

### cargotracker-booking-commandside, book-cargo, success, en
POST http://{{host}}:{{port-commandside}}/cargotracker-booking-commandside/book-cargo
Content-Type: application/json
Accept: application/json
Accept-Charset: utf-8
Accept-Language: en

{
  "originLocation": "HRRJK",
  "destinationLocation": "HRZAG"
}

> {%
// noinspection JSUnresolvedVariable
client.global.set("receivedAggregateIdentifier", response.body.payload.aggregateIdentifier);
%}

### cargotracker-booking-commandside, book-cargo, failure, hr
POST http://{{host}}:{{port-commandside}}/cargotracker-booking-commandside/book-cargo
Content-Type: application/json
Accept: application/json
Accept-Charset: utf-8
Accept-Language: hr-HR

{
  "originLocation": "HRKRK",
  "destinationLocation": "HRZAG"
}

### cargotracker-booking-commandside, book-cargo, failure, en
POST http://{{host}}:{{port-commandside}}/cargotracker-booking-commandside/book-cargo
Content-Type: application/json
Accept: application/json
Accept-Charset: utf-8
Accept-Language: en

{
  "originLocation": "HRKRK",
  "destinationLocation": "HRZAG"
}

###
