### cargotracker-booking-commandside, cargo-booking/book-cargo, validation failure at top level, hr
POST http://{{host}}:{{port-commandside}}/cargotracker-booking-commandside/cargo-booking/book-cargo
Content-Type: application/json
Accept: application/json
Accept-Charset: utf-8
Accept-Language: hr-HR

{
  "routeSpecification": null
}

### cargotracker-booking-commandside, cargo-booking/book-cargo, validation failure at top level, en
POST http://{{host}}:{{port-commandside}}/cargotracker-booking-commandside/cargo-booking/book-cargo
Content-Type: application/json
Accept: application/json
Accept-Charset: utf-8
Accept-Language: en

{
  "routeSpecification": null
}

### cargotracker-booking-commandside, cargo-booking/book-cargo, validation failure at nested level, hr
POST http://{{host}}:{{port-commandside}}/cargotracker-booking-commandside/cargo-booking/book-cargo
Content-Type: application/json
Accept: application/json
Accept-Charset: utf-8
Accept-Language: hr-HR

{
  "routeSpecification": {
    "originLocation": null,
    "destinationLocation": null
  }
}

### cargotracker-booking-commandside, cargo-booking/book-cargo, validation failure at nested level, en
POST http://{{host}}:{{port-commandside}}/cargotracker-booking-commandside/cargo-booking/book-cargo
Content-Type: application/json
Accept: application/json
Accept-Charset: utf-8
Accept-Language: en

{
  "routeSpecification": {
    "originLocation": null,
    "destinationLocation": null
  }
}

### cargotracker-booking-commandside, cargo-booking/book-cargo, success, hr
POST http://{{host}}:{{port-commandside}}/cargotracker-booking-commandside/cargo-booking/book-cargo
Content-Type: application/json
Accept: application/json
Accept-Charset: utf-8
Accept-Language: hr-HR

{
  "routeSpecification": {
    "originLocation": "NLRTM",
    "destinationLocation": "USNYC"
  }
}

> {%
// noinspection JSUnresolvedVariable
client.global.set("receivedCargoIdentifier", response.body.payload.cargoIdentifier);
%}

### cargotracker-booking-commandside, cargo-booking/book-cargo, success, en
POST http://{{host}}:{{port-commandside}}/cargotracker-booking-commandside/cargo-booking/book-cargo
Content-Type: application/json
Accept: application/json
Accept-Charset: utf-8
Accept-Language: en

{
  "routeSpecification": {
    "originLocation": "NLRTM",
    "destinationLocation": "USNYC"
  }
}

> {%
// noinspection JSUnresolvedVariable
client.global.set("receivedCargoIdentifier", response.body.payload.cargoIdentifier);
%}

### cargotracker-booking-commandside, cargo-booking/book-cargo, failure, hr
POST http://{{host}}:{{port-commandside}}/cargotracker-booking-commandside/cargo-booking/book-cargo
Content-Type: application/json
Accept: application/json
Accept-Charset: utf-8
Accept-Language: hr-HR

{
  "routeSpecification": {
    "originLocation": "GRPIR",
    "destinationLocation": "GRATH"
  }
}

### cargotracker-booking-commandside, cargo-booking/book-cargo, failure, en
POST http://{{host}}:{{port-commandside}}/cargotracker-booking-commandside/cargo-booking/book-cargo
Content-Type: application/json
Accept: application/json
Accept-Charset: utf-8
Accept-Language: en

{
  "routeSpecification": {
    "originLocation": "GRPIR",
    "destinationLocation": "GRATH"
  }
}

###
