### cargotracker-booking-queryside, cargo-summary-query, success, hr
POST http://{{host}}:{{port-queryside}}/cargotracker-booking-queryside/cargo-summary
Content-Type: application/json
Accept: application/json
Accept-Charset: utf-8
Accept-Language: hr-HR

{
  "aggregateIdentifier": "{{receivedAggregateIdentifier}}"
}

### cargotracker-booking-queryside, cargo-summary-query, success, en
POST http://{{host}}:{{port-queryside}}/cargotracker-booking-queryside/cargo-summary
Content-Type: application/json
Accept: application/json
Accept-Charset: utf-8
Accept-Language: en

{
  "aggregateIdentifier": "{{receivedAggregateIdentifier}}"
}

### cargotracker-booking-queryside, cargo-summary-query, failure, hr
POST http://{{host}}:{{port-queryside}}/cargotracker-booking-queryside/cargo-summary
Content-Type: application/json
Accept: application/json
Accept-Charset: utf-8
Accept-Language: hr-HR

{
  "aggregateIdentifier": "{{$uuid}}"
}

### cargotracker-booking-queryside, cargo-summary-query, failure, en
POST http://{{host}}:{{port-queryside}}/cargotracker-booking-queryside/cargo-summary
Content-Type: application/json
Accept: application/json
Accept-Charset: utf-8
Accept-Language: en

{
  "aggregateIdentifier": "{{$uuid}}"
}

###
