### cargotracker-booking-queryside, cargo-info/cargo-summary, validation failure, hr
POST http://{{host}}:{{port-queryside}}/cargotracker-booking-queryside/cargo-info/cargo-summary
Content-Type: application/json
Accept: application/json
Accept-Charset: utf-8
Accept-Language: hr-HR

{
  "cargoIdentifier": null
}

### cargotracker-booking-queryside, cargo-info/cargo-summary, validation failure, en
POST http://{{host}}:{{port-queryside}}/cargotracker-booking-queryside/cargo-info/cargo-summary
Content-Type: application/json
Accept: application/json
Accept-Charset: utf-8
Accept-Language: en

{
  "cargoIdentifier": null
}

### cargotracker-booking-queryside, cargo-info/cargo-summary, success, hr
POST http://{{host}}:{{port-queryside}}/cargotracker-booking-queryside/cargo-info/cargo-summary
Content-Type: application/json
Accept: application/json
Accept-Charset: utf-8
Accept-Language: hr-HR

{
  "cargoIdentifier": "{{receivedCargoIdentifier}}"
}

### cargotracker-booking-queryside, cargo-info/cargo-summary, success, en
POST http://{{host}}:{{port-queryside}}/cargotracker-booking-queryside/cargo-info/cargo-summary
Content-Type: application/json
Accept: application/json
Accept-Charset: utf-8
Accept-Language: en

{
  "cargoIdentifier": "{{receivedCargoIdentifier}}"
}

### cargotracker-booking-queryside, cargo-info/cargo-summary, failure, hr
POST http://{{host}}:{{port-queryside}}/cargotracker-booking-queryside/cargo-info/cargo-summary
Content-Type: application/json
Accept: application/json
Accept-Charset: utf-8
Accept-Language: hr-HR

{
  "cargoIdentifier": "{{$uuid}}"
}

### cargotracker-booking-queryside, cargo-info/cargo-summary, failure, en
POST http://{{host}}:{{port-queryside}}/cargotracker-booking-queryside/cargo-info/cargo-summary
Content-Type: application/json
Accept: application/json
Accept-Charset: utf-8
Accept-Language: en

{
  "cargoIdentifier": "{{$uuid}}"
}

###
