package org.klokwrk.lang.groovy.transform

import org.codehaus.groovy.transform.GroovyASTTransformationClass

import java.lang.annotation.ElementType
import java.lang.annotation.Retention
import java.lang.annotation.RetentionPolicy
import java.lang.annotation.Target

/**
 * AST transformation that changes visibility prom public to private for default no-arg constructor generated by {@code @MapConstructor(noArg = true)}.
 * <p/>
 * It can be used standalone, but is commonly used as a part of {@code KwrkImmutable} meta-annotation.
 */
@GroovyASTTransformationClass("org.klokwrk.lang.groovy.transform.KwrkMapConstructorNoArgHideableAstTransformation")
@Retention(RetentionPolicy.RUNTIME)
@Target([ElementType.TYPE])
@interface KwrkMapConstructorNoArgHideable {
  /**
   * Set to false to disable transformation.
   */
  @SuppressWarnings("unused")
  boolean enableNoArgHiding() default true
}
