spring.application.name: booking-commandside-app
server.servlet.context-path: /booking-commandside

server.port: 8080

axon.axonserver.servers: localhost

logging.pattern.console: "${CONSOLE_LOG_PATTERN:%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(${PID:-}){magenta} %clr([%100.100t]){faint} %clr(%-60.60logger{59}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}}"

logging.level.org.axonframework.eventsourcing: DEBUG
logging.level.org.hibernate.SQL: DEBUG  # To see hibernate statements without parameters
logging.level.org.hibernate.type: TRACE # To see parameters bound to hibernate statements
