spring.application.name: booking-queryside-app

server.port: 8084
server.servlet.context-path: /booking-queryside

axon.axonserver.servers: ${CARGO_TRACKER_AXON_SERVER_HOSTNAME:localhost}:${CARGO_TRACKER_AXON_SERVER_PORT_GRPC:8124}

spring.datasource.url: jdbc:postgresql://${CARGO_TRACKER_POSTGRES_HOSTNAME:localhost}:${CARGO_TRACKER_POSTGRES_PORT:5432}/cargo_tracker_query_database
spring.datasource.driverClassName: org.postgresql.Driver
spring.datasource.username: cargotracker
spring.datasource.password: cargotracker

spring.jpa.hibernate.ddl-auto: none
spring.jpa.properties.hibernate.dialect: net.croz.cargotracker.infrastructure.shared.hibernate.dialect.PostgreSqlCustomDialect
spring.jpa.open-in-view: false

logging.pattern.console: "${CONSOLE_LOG_PATTERN:%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(${PID:-}){magenta} %clr([%100.100t]){faint} %clr(%-60.60logger{59}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}}"

logging.level.cargotracker.data-source-proxy.queryLogger: DEBUG
logging.level.cargotracker.data-source-proxy.slowQueryLogger: WARN
logging.level.org.axonframework.eventsourcing: DEBUG
