name: Continuous Integration

on:
  push:
    branches:
      - master
      - feature_*
  pull_request:
    branches:
      - master
      - feature_*

jobs:
  build:
    strategy:
      matrix:
        java: ["8", "11"]
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} - JDK ${{ matrix.java }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache Gradle caches
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-caches-

      - name: Cache Gradle wrapper
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-wrapper-

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Assemble
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: assemble --no-daemon --continue --exclude-task groovydocJar

      - name: Test
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: check --no-daemon --parallel --continue --exclude-task codenarcMain --exclude-task codenarcTest

      - name: CodeNarc
        if: matrix.os == 'ubuntu-latest' && matrix.java == '11'
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: aggregateCodenarcMain aggregateCodenarcTest --no-daemon --continue
