# Main Continuous Integration workflow.
# Basic job steps (until "Publish Test Report") are run on all OSes and JDK versions. Subsequent steps are only for "ubuntu-latest" and JDK 11.

name: Continuous Integration

on:
  push:
    branches:
      - master
      - feature_*
  pull_request:
    branches:
      - master
      - feature_*

jobs:
  build:
    strategy:
      matrix:
        java: ["11", "8"]
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} - JDK ${{ matrix.java }}

    steps:
      - name: Support long paths for Windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: git config --system core.longpaths true

      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache Gradle caches
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ matrix.java }}-${{ matrix.os }}-gradle-caches-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ matrix.java }}-${{ matrix.os }}-gradle-caches-

      - name: Cache Gradle wrapper
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ matrix.java }}-${{ matrix.os }}-gradle-wrapper-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ matrix.java }}-${{ matrix.os }}-gradle-wrapper-

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: ${{ matrix.java }}

      - name: Assemble
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: assemble testClasses testIntegrationClasses --continue --exclude-task groovydoc

      - name: Test Unit
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: check --parallel --continue --exclude-task codenarcMain --exclude-task codenarcTest --exclude-task codenarcTestIntegration

      - name: Test Unit Report
        if: ${{ always() }}
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: aggregateTestReports --exclude-task testIntegration

      - name: Test Unit Report Publish
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: aggregatedTestUnitReports_${{ matrix.os }}-JDK-${{ matrix.java }}
          path: build/reports/aggregate-tests/*

      - name: Test Integration
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: testIntegration --parallel

      - name: CodeNarc
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.java == '11' }}
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: aggregateCodenarc

      - name: Publish CodeNarc Report
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.java == '11' && always() }}
        uses: actions/upload-artifact@v2
        with:
          name: aggregatedCodeNarcReports_${{ matrix.os }}_JDK-${{ matrix.java }}
          path: build/reports/codenarc/*

      - name: JaCoCo Coverage Report
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.java == '11' }}
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: aggregateJacocoReport

      - name: Publish JaCoCo Coverage Report
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.java == '11' }}
        uses: codecov/codecov-action@v1
        with:
          name: Aggregated JaCoCo Report
          file: build/reports/jacoco/aggregate/jacocoTestReport.xml

      - name: Groovydoc
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.java == '11' && github.ref == 'refs/heads/master' && github.event_name == 'push' }}
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: aggregateGroovydoc

      - name: Publish Groovydoc on Gihub Pages
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.java == '11' && github.ref == 'refs/heads/master' && github.event_name == 'push' }}
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          branch: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}
          folder: build/docs/aggregate-groovydoc
          target-folder: groovydoc
          clean: true
          single-commit: true
