name: klokwrk-tool-gradle-source-repack GraalVM native image builder

on: workflow_dispatch

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        include:
          - os: 'ubuntu-latest'
            label: 'linux'
            native-image-name: 'klokwrk-tool-gradle-source-repack'
          - os: 'macos-latest'
            label: 'mac'
            native-image-name: 'klokwrk-tool-gradle-source-repack'
          - os: 'windows-latest'
            label: 'win'
            native-image-name: 'klokwrk-tool-gradle-source-repack.exe'

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} - GraalVM native image build

    steps:
      - name: Support long paths for Windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: git config --system core.longpaths true

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache Gradle caches
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ matrix.os }}-gradle-caches-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ matrix.os }}-gradle-caches-

      - name: Cache Gradle wrapper
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ matrix.os }}-gradle-wrapper-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ matrix.os }}-gradle-wrapper-

      - name: Set up GraalVM
        uses: ayltai/setup-graalvm@v1
        with:
          java-version: 11
          graalvm-version: 20.3.0
          native-image: true

      - name: Assemble
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: --project-dir tool/klokwrk-tool-gradle-source-repack --continue --exclude-task groovydoc clean assemble testClasses

      - name: Test Unit
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: --project-dir tool/klokwrk-tool-gradle-source-repack --continue check

      - name: Jar upload
        uses: actions/upload-artifact@v2
        with:
          name: klokwrk-tool-gradle-source-repack_java
          path: tool/klokwrk-tool-gradle-source-repack/build/libs/*-all.jar

      - name: Build GraalVM native image for mac or linux
        if: ${{ matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'}}
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: --project-dir tool/klokwrk-tool-gradle-source-repack --continue kwrkNativeImage

      - name: Set up Windows - Install Visual C++ Build Tools Workload for Visual Studio 2017 Build Tools
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          choco install visualstudio2017-workload-vctools -y

      - name: Build GraalVM native image for windows
        if: ${{ matrix.os == 'windows-latest' }}
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Vc\Auxiliary\Build\vcvars64.bat"
          ./gradlew.bat --project-dir tool/klokwrk-tool-gradle-source-repack --continue kwrkNativeImage

      - name: GraalVM native image upload
        uses: actions/upload-artifact@v2
        with:
          name: klokwrk-tool-gradle-source-repack_${{ matrix.label }}
          path: tool/klokwrk-tool-gradle-source-repack/build/native-image/${{ matrix.native-image-name }}
